server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meetroom_db
    username: user_meetroom_db
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/master.yml
    enabled: true


