--liquibase formatted sql
--changeset admin_sql:1

CREATE TABLE IF NOT EXISTS public.table_role
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT table_role_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.table_role
    OWNER to user_meetroom_db;

--liquibase formatted sql
--changeset admin_sql:2

CREATE TABLE IF NOT EXISTS public.table_users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    firstname character varying(255) COLLATE pg_catalog."default",
    lastname character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT table_users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_8sy0aajxonivnvttpaoh2w7v7 UNIQUE (username)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.table_users
    OWNER to user_meetroom_db;

--liquibase formatted sql
--changeset admin_sql:3

CREATE TABLE IF NOT EXISTS public.table_users_roles
(
    user_id bigint NOT NULL,
    roles_id bigint NOT NULL,
    CONSTRAINT table_users_roles_pkey PRIMARY KEY (user_id, roles_id),
    CONSTRAINT fko4rpneekym50atkjeniy59n6q FOREIGN KEY (roles_id)
        REFERENCES public.table_role (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkqnd5hp3lv82vcg3kvw5t00ks4 FOREIGN KEY (user_id)
        REFERENCES public.table_users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.table_users_roles
    OWNER to user_meetroom_db;

--liquibase formatted sql
--changeset admin_sql:4

CREATE TABLE IF NOT EXISTS public.table_meetings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date,
    details character varying(255) COLLATE pg_catalog."default",
    length integer,
    start integer,
    id_user bigint,
    CONSTRAINT table_meetings_pkey PRIMARY KEY (id),
    CONSTRAINT fk5p97tv8oh7sqqa1bcw314vppo FOREIGN KEY (id_user)
        REFERENCES public.table_users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.table_meetings
    OWNER to user_meetroom_db;